name: redux_prism
description: Library used to easily access dispatched actions in a Redux Store.
version: 1.0.0
homepage: https://github.com/bgildson/redux_prism

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.8.2
  redux: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
